### ISSUE TITLE
Identify and open-source dependencies

### ISSUE THREAD

**Issue by mfehr** [ethz-asl/hand_eye_calibration#57]
# Here is a complete list of all dependencies:

## 3rd-Party:
 - [x] catkin_simple
 - [x] eigen_catkin
 - [x] gflags_catkin
 - [x] glog_catkin
 - [x] suitesparse
 - [x] doxygen_catkin
 - [x] opencv3_catkin
 - [x] cv_bridge
 - [x] opengv
 - [x] yaml_cpp_catkin

## ASL-Repositories:

[aslam_optimizer](https://github.com/ethz-asl/aslam_optimizer)
 - [x] sparse_block_matrix
 - [x] aslam_backend
 - [x] aslam_backend_expressions

[aslam_splines](https://github.com/ethz-asl/aslam_splines)
 - [x] bsplines
 - [x] aslam_splines

[oomact](https://github.com/ethz-asl/oomact)
 - [x] oomact

[SchweizerMesser](https://github.com/ethz-asl/Schweizer-Messer)
 - [x] sm_common
 - [x] sm_boost
 - [x] sm_logging
 - [x] sm_matrix_archive
 - [x] sm_property_tree
 - [x] sm_random
 - [x] sm_eigen
 - [x] sm_kinematics
 - [x] sm_timing
 - [x] sm_value_store

[asl_cmake_modules](https://github.com/ethz-asl/asl_cmake_modules)
 - [x] asl_cmake_modules

[ethz_apriltag2](https://github.com/ethz-asl/ethzasl_apriltag2)
 - [x] ethzasl_apriltag2

[minkidrn](https://github.com/ethz-asl/minkindr)
 - [x] minkindr

[aslam_cv2](https://github.com/ethz-asl/aslam_cv2)
 - [x] aslam_cv_calibration
 - [x] aslam_cv_geometric_vision
 - [x] aslam_cv_matcher
 - [x] aslam_cv_common_private
 - [x] aslam_cv_common
 - [x] aslam_cv_cameras
 - [x] aslam_cv_frames

**Comment by ffurrer** [comment]
should be resolved now
