### ISSUE TITLE
missing libnabo in rosinstall

### ISSUE THREAD

**Issue by panjekm** [ethz-asl/hand_eye_calibration#68]
git@github.com:ethz-asl/libnabo.git

**Comment by mfehr** [comment]
@panjekm are you sure this is required if you only build hand_eye_calibration packages?
I know it's required by some aslam_cv packages, but not sure we depend on those.

**Comment by panjekm** [comment]
it complained while trying to run the command thats in instructions:
`catkin build hand_eye_calibration hand_eye_calibration_target_extractor hand_eye_calibration_batch_estimation`

**Comment by mfehr** [comment]
https://github.com/ethz-asl/hand_eye_calibration/pull/70
