### ISSUE TITLE
Wrong Hand-Eye Calibration Results

### ISSUE THREAD

**Issue by SebNag** [ethz-asl/hand_eye_calibration#78]
Thanks a lot for making the code / work publicly available ! 

After installing the packages I followed the [Step-by-Step Calibration Tutorial](https://github.com/ethz-asl/hand_eye_calibration#user-content-step-by-step-calibration). 

I am using a UR5 Robot together with [this ur driver](https://github.com/Zagitta/ur_modern_driver), driving at various positions, recording the published transformations between the base link and the end-effector in a ros bag. 
At the same time I have an aprilgrid board mounted at the robot and a camera placed next to the robot, recording frames in a ros bag ( the board looks a bit weird since it is truncated ).

From a camera viewpoint: 

![setup_calibration](https://user-images.githubusercontent.com/12411175/42942240-8708e768-8b5f-11e8-8a71-4bef11c981f2.png)

Both transformation ( Base <-> Hand and World <-> Eye ) seem to be correct. However, performing the dual-quaternion-based hand-eye calibration results in a completely wrong calibration ( does not make any sense at all ). 
I tried the same procedure with a camera mounted on the robot and the grid being fixed somewhere in the world, however the calibration does not make any sense either. 

Am I using the calibration procedure as intended or am I missing something crucial ? 
Thanks for your help ! 

----

All tests do pass. 
When building the repository I had some linker issues:  

![linker_error](https://user-images.githubusercontent.com/12411175/42942146-59a0bbe8-8b5f-11e8-9040-6991334b481b.png)

Which resolved after I added 

`target_link_libraries(${PROJECT_NAME} -lblas -llapack -lsuitesparseconfig)`

to the `CMakeLists.txt` file in 

`[...]/workspace_calibration/src/aslam_optimizer/aslam_backend_expressions`

**Comment by SebNag** [comment]
Seems to be more of an issue in the tf-data from the controller rather than something in the calibration code.

**Comment by smauq** [comment]
FYI, linker issues are related to this issue https://github.com/ethz-asl/suitesparse/issues/29
A more clean solution is to revert to this commit of suiteparse until it's fixed https://github.com/ethz-asl/suitesparse/tree/df17ac067de83f9a126ac4c121e0fd245bbf8ad1 (probably no effect on the results though)

**Comment by HannesSommer** [comment]
Update: Issue ethz-asl/suitesparse#29 has been solved in the meantime. There should be no need for an explicit ` -lblas -llapack -lsuitesparseconfig` anymore.
