### ISSUE TITLE
something about function calculate_time_offset

### ISSUE THREAD

**Issue by szzadkk** [ethz-asl/hand_eye_calibration#88]
#### Get the two mean time steps. Take the smaller one for the interpolation.
  dt_A = np.mean(np.diff(times_A))
  dt_B = np.mean(np.diff(times_B))
  if dt_A >= dt_B:
    dt = dt_A
  else:
    dt = dt_B
I note that the comment take the smaller one, but the code takes the bigger one....

**Comment by bacalfa** [comment]
Same thing appears to happen in function `compute_aligned_poses` (note the `>=` sign):

https://github.com/ethz-asl/hand_eye_calibration/blob/5e2b6c9f0ec93ecf5a67d71a2d9eb647ac47adad/hand_eye_calibration/python/hand_eye_calibration/time_alignment.py#L240-L250

**Comment by bacalfa** [comment]
Actually, frequency is the inverse of time. So "lower frequency" means `<=` when comparing arrays in the time domain.

**Comment by szzadkk** [comment]
> Actually, frequency is the inverse of time. So "lower frequency" means `<=` when comparing arrays in the time domain

**Comment by szzadkk** [comment]
> Actually, frequency is the inverse of time. So "lower frequency" means `<=` when comparing arrays in the time domain.

I make a mistake, and get it now, thank you!
