### ISSUE TITLE
about the trajectory to move the manipulator

### ISSUE THREAD

**Issue by XiaoshanLin9701** [ethz-asl/hand_eye_calibration#90]
Hi, I am trying to use your tool for hand-eye calibration but do not get a good result. I place a 4 by 5 Aruco board on the desk and move the manipulator around the Aruco board to create my own csv files. But when I run the code to calibrate the camera, it throw the following warning: 
"The singular values of this solution are bad. Either the smallest two are too big or the first 6 are too small! "
And the result of the calibration is very poor. The resulting transformation matrix is totally different from the one I get using Tsai's method.

Is that because the trajectory I choose for the manipulator is not good enough, or I don't have enough data in the csv files? The trajectory is chosen randomly, and I have 40 poses in each csv file.   

![1869725925](https://user-images.githubusercontent.com/41238049/53386437-34443c00-39bd-11e9-8efd-388fb9f3a164.jpg)

**Comment by XiaoshanLin9701** [comment]
Made a big mistake. I used the the pose of the aruco calibration board instead of the camera pose in reference to the world frame.

**Comment by johnjin404** [comment]
hello ,,i also got this problem, but , i use the camera_pose indeed,,here is my aligned_data

[camera_aligned.txt](https://github.com/ethz-asl/hand_eye_calibration/files/3614533/camera_aligned.txt)
[vicon_aligned.txt](https://github.com/ethz-asl/hand_eye_calibration/files/3614534/vicon_aligned.txt)

I need to use this package to calibrate extrinsic param between the realsense camera and the vicon markers(rigidbody) stick on the camera.
data describtion:
     vicon_aligned:  --poses_B_H_csv_file
     camera_aligned:  --poses_W_E_csv_file (localize the camera with one ARUCO marker)

After the calibration routings ,I got this 
       The singular values of this solution are bad. Either the smallest two are too big or the first 6 are too small! singular values: [ 5.61685252  5.00851638  4.4412948   4.10509097  3.46701731  3.09330403
  1.82952841  1.55362262]

Do u know how to solve this?Is there any problem about the data collecting.Thank you!
